FROM python:3.12

WORKDIR /app

COPY . .

RUN pip install \
    fastapi \
    uvicorn \
    redis \
    faiss-cpu \
    numpy

CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8005"]