name: Security Scan

on:
  schedule:
    - cron: "0 2 * * *"

jobs:

  dependency-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master

        with:
          scan-type: fs
          scan-ref: .